---
title: "Revised Visualization"
author: "Team 9"
date: "9/28/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
homework3 <- read_csv("part_1/homework3.csv")
```


```{r, include=FALSE}
#create dataframe

colnames(homework3)[1]="Faculty type"
FacultyPercent <-matrix(nrow=55,ncol=3,data=NA)
FacultyPercent[,1]<-rep(homework3$`Faculty type`,11)
FacultyPercent[,2]<-c(sapply(colnames(homework3)[-1],function(x) {rep(x,5)}))
FacultyPercent[,3] <- c(sapply(homework3[,-1],print))
FacultyPercent<-as.data.frame(FacultyPercent)
colnames(FacultyPercent)=c("ftype","year","percent")
FacultyPercent$percent=as.double(as.character(FacultyPercent$percent))
```


```{r, echo=FALSE}
#draw plot

ggplot(FacultyPercent,aes(x=year,y=percent))+
  geom_line(aes(x=year,y=percent,group=ftype,color=ftype), linetype="dashed")+
  geom_point(size=1, alpha=0.5)+
  theme_bw()+
  theme(legend.text=element_text(size=7), legend.justification = c(1,0), legend.position = c(1,.42),plot.title = element_text(hjust = 0.5))+
  labs(title = "Instructional Staff Employment Trends", x = "Year", y = "Percentage of Faculty", colour = "Faculty Type")

```


